apiVersion: batch/v1
kind: Job
metadata:
  name: mq-test
  namespace: mq
spec:
  selector: {}
  template:
    metadata:
      name: mq-test
    spec:
      containers:
        - name: mq-test
          image: image-registry.openshift-image-registry.svc:5000/mq/testing:latest
          command:
            - print 'testing done'
      restartPolicy: Never